added : swedish aidon meter support
stevew817/ams-han-parser pull request #3
Opened 2024-02-28 04:43 UTC by HareshPrajapati

Please review the AIDON 3-phase Energy Service Device that I have added.

2024-02-28 07:51 UTC, stevew817 commented
Thank you for the contribution! But I have to ask: did you run a code formatter on the file? There's a lot of whitespace changes making it difficult to review.

2024-02-28 08:04 UTC, stevew817 requested changes

2024-02-28 08:04 UTC, stevew817 commented on known_lists.c
> +	0203 0906 0100020700ff 06 00000000 0202 0f00 161b
Any reason for the indent here?

2024-02-28 08:04 UTC, stevew817 commented on known_lists.c
> +const ams_known_list_ids_mapping_t aidon_h0001_mapping = {
Please move this inside the #ifndef DISABLE_AIDON block. You're adding an Aidon meter after all, so if whoever is compiling this doesn't care about Aidon, they should be able to compile it out.

2024-02-28 08:04 UTC, stevew817 commented on known_lists.h
> +#ifndef DISABLE_KAIFA
This doesn't look right... Why is an Aidon meter variant inside a DISABLE_KAIFA block?

2024-02-28 08:04 UTC, stevew817 commented on hanparser.c
> +static uint8_t input_buffer[2048];
Any reason for 2048? Your sample message was 581 if I counted correctly, so this could be e.g. 640 and not waste static RAM allocation on constrained devices?

2024-02-28 08:04 UTC, stevew817 commented on hanparser.c
> +  // Variable to track the last seen meter type, to avoid string matching too much
Comment valid throughout: there's a lot of whitespace changes, making it look like you used a formatter with a style definition that didn't match the code style in use. Could you check your formatter settings to see if you could match style? Or even better - turn off the formatter for now so that I can see exactly what was changed here?

2024-02-28 13:14 UTC, HareshPrajapati commented on hanparser.c
> +static uint8_t input_buffer[2048];
No, it will be around 1060 so i am making it to 1100

2024-02-29 01:20 UTC, stevew817 requested changes

2024-02-29 01:20 UTC, stevew817 commented on hanparser.c
Thank you for the updated PR, but the diff for this file still contains way too much whitespace changes. Is the only actual change you made in this file the size of the input buffer? It looks that way, but I'm not sure due to all the rearranging and the change in tabsize...

If that's the case, I'd appreciate it if you could keep the original formatting intact and only change the buffer size? That'd make for a much cleaner PR.

2024-02-29 22:53 UTC, stevew817 approved these changes
Thanks, looks good!

2024-02-29 22:54 UTC, merged